/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.13.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./JunoSwap.types";
import * as _1 from "./JunoSwap.client";
import * as _2 from "./JunoSwap.react-query";
export namespace contracts {
  export const JunoSwap = { ..._0,
    ..._1,
    ..._2
  };
}