/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.13.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
import * as _0 from "./JunoSwap.types";
import * as _1 from "./JunoSwap.client";
import * as _2 from "./JunoSwap.react-query";
export declare namespace contracts {
    const JunoSwap: {
        useJunoSwapToken2ForToken1PriceQuery<TData = _0.Token2ForToken1PriceResponse>({ client, args, options }: _2.JunoSwapToken2ForToken1PriceQuery<TData>): import("@tanstack/react-query").UseQueryResult<TData, Error>;
        useJunoSwapToken1ForToken2PriceQuery<TData_1 = _0.Token1ForToken2PriceResponse>({ client, args, options }: _2.JunoSwapToken1ForToken2PriceQuery<TData_1>): import("@tanstack/react-query").UseQueryResult<TData_1, Error>;
        useJunoSwapInfoQuery<TData_2 = _0.InfoResponse>({ client, options }: _2.JunoSwapInfoQuery<TData_2>): import("@tanstack/react-query").UseQueryResult<TData_2, Error>;
        useJunoSwapBalanceQuery<TData_3 = _0.BalanceResponse>({ client, args, options }: _2.JunoSwapBalanceQuery<TData_3>): import("@tanstack/react-query").UseQueryResult<TData_3, Error>;
        useJunoSwapSwapToMutation(options?: Omit<import("@tanstack/react-query").UseMutationOptions<import("@cosmjs/cosmwasm-stargate").ExecuteResult, Error, _2.JunoSwapSwapToMutation, unknown>, "mutationFn">): import("@tanstack/react-query").UseMutationResult<import("@cosmjs/cosmwasm-stargate").ExecuteResult, Error, _2.JunoSwapSwapToMutation, unknown>;
        useJunoSwapMultiContractSwapMutation(options?: Omit<import("@tanstack/react-query").UseMutationOptions<import("@cosmjs/cosmwasm-stargate").ExecuteResult, Error, _2.JunoSwapMultiContractSwapMutation, unknown>, "mutationFn">): import("@tanstack/react-query").UseMutationResult<import("@cosmjs/cosmwasm-stargate").ExecuteResult, Error, _2.JunoSwapMultiContractSwapMutation, unknown>;
        useJunoSwapSwapToken2ForToken1Mutation(options?: Omit<import("@tanstack/react-query").UseMutationOptions<import("@cosmjs/cosmwasm-stargate").ExecuteResult, Error, _2.JunoSwapSwapToken2ForToken1Mutation, unknown>, "mutationFn">): import("@tanstack/react-query").UseMutationResult<import("@cosmjs/cosmwasm-stargate").ExecuteResult, Error, _2.JunoSwapSwapToken2ForToken1Mutation, unknown>;
        useJunoSwapSwapToken1ForToken2Mutation(options?: Omit<import("@tanstack/react-query").UseMutationOptions<import("@cosmjs/cosmwasm-stargate").ExecuteResult, Error, _2.JunoSwapSwapToken1ForToken2Mutation, unknown>, "mutationFn">): import("@tanstack/react-query").UseMutationResult<import("@cosmjs/cosmwasm-stargate").ExecuteResult, Error, _2.JunoSwapSwapToken1ForToken2Mutation, unknown>;
        useJunoSwapRemoveLiquidityMutation(options?: Omit<import("@tanstack/react-query").UseMutationOptions<import("@cosmjs/cosmwasm-stargate").ExecuteResult, Error, _2.JunoSwapRemoveLiquidityMutation, unknown>, "mutationFn">): import("@tanstack/react-query").UseMutationResult<import("@cosmjs/cosmwasm-stargate").ExecuteResult, Error, _2.JunoSwapRemoveLiquidityMutation, unknown>;
        useJunoSwapAddLiquidityMutation(options?: Omit<import("@tanstack/react-query").UseMutationOptions<import("@cosmjs/cosmwasm-stargate").ExecuteResult, Error, _2.JunoSwapAddLiquidityMutation, unknown>, "mutationFn">): import("@tanstack/react-query").UseMutationResult<import("@cosmjs/cosmwasm-stargate").ExecuteResult, Error, _2.JunoSwapAddLiquidityMutation, unknown>;
        JunoSwapQueryClient: typeof _1.JunoSwapQueryClient;
        JunoSwapClient: typeof _1.JunoSwapClient;
    };
}
