/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.10.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
import * as _1 from "./JunoSwap.client";
import * as _2 from "./JunoSwap.react-query";
export declare namespace contracts {
    const JunoSwap: {
        useJunoSwapToken2ForToken1PriceQuery({ client, args, options }: _2.JunoSwapToken2ForToken1PriceQuery): any;
        useJunoSwapToken1ForToken2PriceQuery({ client, args, options }: _2.JunoSwapToken1ForToken2PriceQuery): any;
        useJunoSwapInfoQuery({ client, options }: _2.JunoSwapInfoQuery): any;
        useJunoSwapBalanceQuery({ client, args, options }: _2.JunoSwapBalanceQuery): any;
        useJunoSwapSwapToMutation(options?: Omit<UseMutationOptions<ExecuteResult, Error, _2.JunoSwapSwapToMutation>, "mutationFn">): any;
        useJunoSwapMultiContractSwapMutation(options?: Omit<UseMutationOptions<ExecuteResult, Error, _2.JunoSwapMultiContractSwapMutation>, "mutationFn">): any;
        useJunoSwapSwapToken2ForToken1Mutation(options?: Omit<UseMutationOptions<ExecuteResult, Error, _2.JunoSwapSwapToken2ForToken1Mutation>, "mutationFn">): any;
        useJunoSwapSwapToken1ForToken2Mutation(options?: Omit<UseMutationOptions<ExecuteResult, Error, _2.JunoSwapSwapToken1ForToken2Mutation>, "mutationFn">): any;
        useJunoSwapRemoveLiquidityMutation(options?: Omit<UseMutationOptions<ExecuteResult, Error, _2.JunoSwapRemoveLiquidityMutation>, "mutationFn">): any;
        useJunoSwapAddLiquidityMutation(options?: Omit<UseMutationOptions<ExecuteResult, Error, _2.JunoSwapAddLiquidityMutation>, "mutationFn">): any;
        JunoSwapQueryClient: typeof _1.JunoSwapQueryClient;
        JunoSwapClient: typeof _1.JunoSwapClient;
    };
}
