/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.16.4.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
import * as _1 from "./JunoSwap.client";
import * as _2 from "./JunoSwap.message-composer";
export declare namespace contracts {
    const JunoSwap: {
        JunoSwapMessageComposer: typeof _2.JunoSwapMessageComposer;
        JunoSwapQueryClient: typeof _1.JunoSwapQueryClient;
        JunoSwapClient: typeof _1.JunoSwapClient;
    };
}
